begin refactoring

diff --git a/2ls-wrapper b/2ls-wrapper
--- a/2ls-wrapper
+++ b/2ls-wrapper
@@ -1,48 +1,82 @@
 #!/bin/bash
 # tool
 
-TOOL_BINARY=./src/cbmc/cbmc
-TOOL_NAME=CBMC
+TOOL_BINARY=../2ls_cadical/2ls/src/2ls/2ls
+GOTO_CC=../2ls_cadical/2ls/lib/cbmc/src/goto-cc/goto-cc
+GOTO_INSTRUMENT=../2ls_cadical/2ls/lib/cbmc/src/goto-instrument/goto-instrument
+TOOL_NAME=2LS
 FIND_OPTIONS=""
 
 # function to run the tool
 
 run()
 {
-  if [ "$PROP" = "termination" ] ; then
-    PROPERTY="$PROPERTY --no-assertions --no-self-loops-to-assumptions"
-  fi
-
   gmon_suffix=$GMON_OUT_PREFIX
   export GMON_OUT_PREFIX="goto-cc_$gmon_suffix"
-  ./src/goto-cc/goto-cc --verbosity 9 -m$BIT_WIDTH --function $ENTRY "${BM[@]}" -o $LOG.bin
+  $GOTO_CC -m$BIT_WIDTH --function $ENTRY "${BM[@]}" -o $LOG.bin
   if [ -n "$FAIL_FUNCTION" ]; then
-    ./src/goto-instrument/goto-instrument $LOG.bin $LOG.bin --remove-function-body "$FAIL_FUNCTION" \
-                                        --verbosity 9 --generate-function-body "$FAIL_FUNCTION" \
+    $GOTO_INSTRUMENT $LOG.bin $LOG.bin --remove-function-body "$FAIL_FUNCTION" \
+                                        --generate-function-body "$FAIL_FUNCTION" \
                                         --generate-function-body-options assert-false
   fi
 
-  export GMON_OUT_PREFIX="cbmc_$gmon_suffix"
-timeout 875 bash -c ' \
-\
-ulimit -v 64000000 ; \
-\
-EC=42 ; \
-echo "./src/cbmc/cbmc --incremental-loop main.0 --unwind-max 100 --no-standard-checks --verbosity 9 --slice-formula --stop-on-fail --object-bits $OBJ_BITS $PROPERTY"; \
-./src/cbmc/cbmc --incremental-loop main.0 --unwind-max 100 --no-standard-checks --verbosity 9 --slice-formula  --stop-on-fail --object-bits $OBJ_BITS $PROPERTY $LOG.bin >> $LOG.latest 2>&1 ; \
-ec=$? ; \
-\
-case $ec in \
-0) EC=0 ; cat $LOG.latest >> $LOG.ok ; echo "EC=$EC" >> $LOG.ok ;; \
-10) EC=10 ; cat $LOG.latest >> $LOG.ok ; echo "EC=$EC" >> $LOG.ok ;; \
-42) EC=42 ; cat $LOG.latest >> $LOG.ok ; rm -f $LOG.latest ; echo "EC=$EC" >> $LOG.ok ;; \
-*) if [ $EC -ne 0 ] ; then EC=$ec ; cat $LOG.latest >>$LOG.ok ; fi ; echo "EC=$EC" >> $LOG.ok ;; \
-esac ; \
-'
-  if [ ! -s $LOG.ok ] ; then
-    mv $LOG.latest $LOG.ok ; echo "EC=42" >> $LOG.ok
+  export GMON_OUT_PREFIX="2ls_$gmon_suffix"
+  # add property-specific options
+  if [[ "$PROP" == "termination" ]]; then
+    PROPERTY1="$PROPERTY --termination --competition-mode"
+    PROPERTY2="$PROPERTY --nontermination --competition-mode"
+
+    # run the termination and nontermination analysis in parallel
+    $TOOL_BINARY --graphml-witness $LOG.witness --object-bits $OBJ_BITS $PROPERTY1 \
+      $LOG.bin >> $LOG.ok1 2>&1 &
+    PID1="$!"
+    $TOOL_BINARY --graphml-witness $LOG.witness --object-bits $OBJ_BITS $PROPERTY2 \
+      $LOG.bin >> $LOG.ok2 2>&1 &
+    PID2="$!"
+    # this might not work in all environments
+    wait -n &> /dev/null
+
+    # store the exit code of the first process that is finished
+    EC=$?
+
+    # find out which one has finished
+    for pid in $PID1 $PID2
+    do
+      if ! ps -p $pid &> /dev/null; then
+        EXITED=$pid
+        break
+      fi
+    done
+
+    # if the result of the first exiting analysis is inconclusive
+    # then wait for the other analysis to finish
+    if [ $EC -eq 5 ]; then
+      wait -n &> /dev/null
+      EC=$?
+      if [[ "$EXITED" == "$PID1" ]]; then
+        mv $LOG.ok2 $LOG.ok
+      else
+        mv $LOG.ok1 $LOG.ok
+      fi
+    else # we have a conclusive result, kill the other process
+      if [[ "$EXITED" == "$PID1" ]]; then
+        kill -9 $PID2 &> /dev/null
+        mv $LOG.ok1 $LOG.ok
+      else
+        kill -9 $PID1  &> /dev/null
+        mv $LOG.ok2 $LOG.ok
+      fi
+    fi
+  else
+    PROPERTY="$PROPERTY --heap --arrays --values-refine --k-induction --competition-mode"
+
+    # run the tool
+    $TOOL_BINARY --graphml-witness $LOG.witness --object-bits $OBJ_BITS $PROPERTY \
+      $LOG.bin >> $LOG.ok 2>&1
+
+    # store the exit code
+    EC=$?
   fi
-  eval `tail -n 1 $LOG.ok`
 }
 
 # main tool wrapper script
diff --git a/cbmc-wrapper b/cbmc-wrapper
--- a/cbmc-wrapper
+++ b/cbmc-wrapper
@@ -1,7 +1,9 @@
 #!/bin/bash
 # tool
 
-TOOL_BINARY=./src/cbmc/cbmc
+TOOL_BINARY=../cbmc_cadical/cbmc/src/cbmc/cbmc
+GOTO_CC=../cbmc_cadical/cbmc/src/goto-cc/goto-cc
+GOTO_INSTRUMENT=../cbmc_cadical/cbmc/src/goto-instrument/goto-instrument
 TOOL_NAME=CBMC
 FIND_OPTIONS=""
 
@@ -15,26 +17,27 @@ run()
 
   gmon_suffix=$GMON_OUT_PREFIX
   export GMON_OUT_PREFIX="goto-cc_$gmon_suffix"
-  ./src/goto-cc/goto-cc --verbosity 9 -m$BIT_WIDTH --function $ENTRY "${BM[@]}" -o $LOG.bin
+  $GOTO_CC -m$BIT_WIDTH --function $ENTRY "${BM[@]}" -o $LOG.bin
   if [ -n "$FAIL_FUNCTION" ]; then
-    ./src/goto-instrument/goto-instrument $LOG.bin $LOG.bin --remove-function-body "$FAIL_FUNCTION" \
-                                        --verbosity 9 --generate-function-body "$FAIL_FUNCTION" \
+    $GOTO_INSTRUMENT $LOG.bin $LOG.bin --remove-function-body "$FAIL_FUNCTION" \
+                                        --generate-function-body "$FAIL_FUNCTION" \
                                         --generate-function-body-options assert-false
   fi
 
   export GMON_OUT_PREFIX="cbmc_$gmon_suffix"
+
 timeout 875 bash -c ' \
 \
 ulimit -v 64000000 ; \
 \
 EC=42 ; \
 for c in 2 6 12 17 21 40 200 400 1025 2049 268435456 ; do \
-echo "Unwind: $c" >> $LOG.latest ; \
-./src/cbmc/cbmc --no-standard-checks --verbosity 9 --slice-formula --unwind $c --stop-on-fail --object-bits $OBJ_BITS $PROPERTY $LOG.bin >> $LOG.latest 2>&1 ; \
-ec=$? ; \
+echo "Unwind: $c" | tee -a $LOG.latest ; \
+$TOOL_BINARY --no-standard-checks --slice-formula --unwind $c --stop-on-fail --object-bits $OBJ_BITS $PROPERTY $LOG.bin 2>&1 | tee -a $LOG.latest ; \
+ec=${PIPESTATUS[0]} ; \
 if [ $ec -eq 0 ] ; then \
 if ! tail -n 10 $LOG.latest | grep -q "^VERIFICATION SUCCESSFUL$" ; then ec=1 ; else \
-./src/cbmc/cbmc --no-standard-checks --verbosity 9 --slice-formula --unwinding-assertions --unwind $c --stop-on-fail --object-bits $OBJ_BITS $PROPERTY $LOG.bin >> $LOG.latest 2>&1 || ec=42 ; \
+$TOOL_BINARY --no-standard-checks --slice-formula --unwinding-assertions --unwind $c --stop-on-fail --object-bits $OBJ_BITS $PROPERTY $LOG.bin 2>&1 | tee -a $LOG.latest || ec=42 ; \
 fi ; \
 fi ; \
 if [ $ec -eq 10 ] ; then \
@@ -42,16 +45,16 @@ if ! tail -n 10 $LOG.latest | grep -q "^VERIFICATION FAILED$" ; then ec=1 ; fi ;
 fi ; \
 \
 case $ec in \
-0) EC=0 ; cat $LOG.latest >> $LOG.ok ; echo "EC=$EC" >> $LOG.ok ; break ;; \
-10) EC=10 ; cat $LOG.latest >> $LOG.ok ; echo "EC=$EC" >> $LOG.ok ; break ;; \
+0) EC=0 ; cat $LOG.latest >> $LOG.ok ; echo "EC=$EC" | tee -a $LOG.ok ; break ;; \
+10) EC=10 ; cat $LOG.latest >> $LOG.ok ; echo "EC=$EC" | tee -a $LOG.ok ; break ;; \
 42) EC=42 ; cat $LOG.latest >> $LOG.ok ; rm -f $LOG.latest ;; \
-*) if [ $EC -ne 0 ] ; then EC=$ec ; cat $LOG.latest >>$LOG.ok ; fi ; echo "EC=$EC" >> $LOG.ok ; break ;; \
+*) if [ $EC -ne 0 ] ; then EC=$ec ; cat $LOG.latest >>$LOG.ok ; fi ; echo "EC=$EC" | tee -a $LOG.ok ; break ;; \
 esac ; \
 \
 done \
 '
   if [ ! -s $LOG.ok ] ; then
-    mv $LOG.latest $LOG.ok ; echo "EC=42" >> $LOG.ok
+    mv $LOG.latest $LOG.ok ; echo "EC=42" | tee -a $LOG.ok
   fi
   eval `tail -n 1 $LOG.ok`
 }
@@ -223,13 +226,13 @@ export BM_DIR=`mktemp -d -t ${TOOL_NAME}-benchmark.XXXXXX`
 export LOG=`mktemp -t ${TOOL_NAME}-log.XXXXXX`
 trap "rm -rf $LOG $LOG.latest $LOG.ok $LOG.witness $LOG.bin $BM_DIR" EXIT
 
-run
+time run
 
 if [ ! -s $LOG.ok ] ; then
   exit 1
 fi
 
-cat $LOG.ok
+#cat $LOG.ok
 case $EC in
   0) if [[ "$WITNESS_FILE" != "" ]]; then process_graphml $EC > $WITNESS_FILE; \
 fi; echo "TRUE" ;;
diff --git a/mallob-2ls-wrapper b/mallob-2ls-wrapper
--- a/mallob-2ls-wrapper
+++ b/mallob-2ls-wrapper
@@ -1,51 +1,94 @@
 #!/bin/bash
 # tool
-
-TOOL_BINARY=./lib/cbmc/src/cbmc/cbmc
-TOOL_NAME=CBMC_MALLOB
+MALLOB=../cbmc_mallob_monolithic/mallob
+BACK=../../benchmark_bmc
+TOOL_BINARY=./build_2ls/mallob
+GOTO_CC=$MALLOB/lib/2ls/lib/cbmc/src/goto-cc/goto-cc
+GOTO_INSTRUMENT=$MALLOB/lib/2ls/lib/cbmc/src/goto-instrument/goto-instrument
+TOOL_NAME=MALLOB_2LS
 FIND_OPTIONS=""
 
 # function to run the tool
 
 run()
 {
-  if [ "$PROP" = "termination" ] ; then
-    PROPERTY="$PROPERTY --no-assertions --no-self-loops-to-assumptions"
-  fi
-
+  SECONDS=0
   gmon_suffix=$GMON_OUT_PREFIX
   export GMON_OUT_PREFIX="goto-cc_$gmon_suffix"
-  ./lib/cbmc/src/goto-cc/goto-cc --verbosity 9 -m$BIT_WIDTH --function $ENTRY "${BM[@]}" -o $LOG.bin
+  $GOTO_CC -m$BIT_WIDTH --function $ENTRY "${BM[@]}" -o $LOG.bin
   if [ -n "$FAIL_FUNCTION" ]; then
-    ./lib/cbmc/src/goto-instrument/goto-instrument $LOG.bin $LOG.bin --remove-function-body "$FAIL_FUNCTION" \
-                                        --verbosity 9 --generate-function-body "$FAIL_FUNCTION" \
+    $GOTO_INSTRUMENT $LOG.bin $LOG.bin --remove-function-body "$FAIL_FUNCTION" \
+                                        --generate-function-body "$FAIL_FUNCTION" \
                                         --generate-function-body-options assert-false
   fi
+  duration=$SECONDS
+  export GMON_OUT_PREFIX="2ls_$gmon_suffix"
 
-  export GMON_OUT_PREFIX="cbmc_$gmon_suffix"
-  
-  # Replace spaces with commas in PROPERTY for mallob
-  echo "PROPERTY: $PROPERTY"
-  PROPERTY=$(echo "$PROPERTY" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
-  PROPERTY=$(echo "$PROPERTY" | sed "s/ /,/g")
-  echo "PROPERTY: $PROPERTY"
+  # add property-specific options
+  if [[ "$PROP" == "termination" ]]; then
+    echo "Not supported yet"
+    # PROPERTY1="$PROPERTY --termination --competition-mode"
+    # PROPERTY2="$PROPERTY --nontermination --competition-mode"
 
-timeout 875 bash -c ' \
-\
-ulimit -v 64000000 ; \
-\
-echo "Running mallob" >> $LOG.latest ; \
-ec=42 ; \
-./build/mallob -t=16 -mono-app=CBMC -mono=$LOG.bin -v=4 -compress-models -s2f=$LOG.latest -cbmc-opts=--incremental-loop,main.0,--unwind-max,100,--no-standard-checks,--verbosity,9,--slice-formula,--stop-on-fail,--object-bits,$OBJ_BITS,$PROPERTY ; \
-if grep -q "EC=" $LOG.latest; then ec=$(grep -o "EC=[0-9]*" $LOG.latest | tail -n1 | cut -d'=' -f2 | tr -d '[:space:]'); else ec=1; fi ; \
-#echo "Exit code: $ec" ; \
-mv $LOG.latest $LOG.ok ; \
-#echo "EC=$ec" >> $LOG.ok ; \
-'
-  if [ ! -s $LOG.ok ] ; then
-    mv $LOG.latest $LOG.ok ; echo "EC=42" >> $LOG.ok
+    # # run the termination and nontermination analysis in parallel
+    # $TOOL_BINARY --graphml-witness $LOG.witness --object-bits $OBJ_BITS $PROPERTY1 \
+    #   $LOG.bin >> $LOG.ok1 2>&1 &
+    # PID1="$!"
+    # $TOOL_BINARY --graphml-witness $LOG.witness --object-bits $OBJ_BITS $PROPERTY2 \
+    #   $LOG.bin >> $LOG.ok2 2>&1 &
+    # PID2="$!"
+    # # this might not work in all environments
+    # wait -n &> /dev/null
+
+    # # store the exit code of the first process that is finished
+    # EC=$?
+
+    # # find out which one has finished
+    # for pid in $PID1 $PID2
+    # do
+    #   if ! ps -p $pid &> /dev/null; then
+    #     EXITED=$pid
+    #     break
+    #   fi
+    # done
+
+    # # if the result of the first exiting analysis is inconclusive
+    # # then wait for the other analysis to finish
+    # if [ $EC -eq 5 ]; then
+    #   wait -n &> /dev/null
+    #   EC=$?
+    #   if [[ "$EXITED" == "$PID1" ]]; then
+    #     mv $LOG.ok2 $LOG.ok
+    #   else
+    #     mv $LOG.ok1 $LOG.ok
+    #   fi
+    # else # we have a conclusive result, kill the other process
+    #   if [[ "$EXITED" == "$PID1" ]]; then
+    #     kill -9 $PID2 &> /dev/null
+    #     mv $LOG.ok1 $LOG.ok
+    #   else
+    #     kill -9 $PID1  &> /dev/null
+    #     mv $LOG.ok2 $LOG.ok
+    #   fi
+    # fi
+  else
+    PROPERTY="$PROPERTY --heap --arrays --values-refine --k-induction --competition-mode"
+
+    # Replace spaces with commas in PROPERTY for mallob
+    echo "PROPERTY: $PROPERTY"
+    PROPERTY=$(echo "$PROPERTY" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+    PROPERTY=$(echo "$PROPERTY" | sed "s/ /,/g")
+    echo "PROPERTY: $PROPERTY"
+
+    cd $MALLOB
+    # run the tool
+    $TOOL_BINARY -t=16 -mono-app=2ls -mono=$LOG.bin -v=4 -compress-models -s2f=$LOG.ok -2ls-opts=--graphml-witness,$LOG.witness,--object-bits,$OBJ_BITS,$PROPERTY ;\
+    if grep -q "s EC=" $LOG.ok; then EC=$(grep -o "s EC=[0-9]*" $LOG.ok | tail -n1 | cut -d'=' -f2 | tr -d '[:space:]'); else EC=5; fi ; \
+    echo $EC
+    echo "t COMPILE_TIME: $duration" >> $LOG.ok
+
+    cd $BACK
   fi
-  eval `tail -n 1 $LOG.ok`
 }
 
 # main tool wrapper script
