new wrappers

diff --git a/cbmc-minisat-wrapper b/cbmc-minisat-wrapper
--- a/cbmc-minisat-wrapper
+++ b/cbmc-minisat-wrapper
@@ -1,11 +1,10 @@
 #!/bin/bash
 # tool
-MALLOB=../mallob_bmc/mallob_newstream/mallob
-BACK=../../benchmark_bmc
-TOOL_BINARY=./build_cbmc/mallob
-GOTO_CC=$MALLOB/lib/cbmc/src/goto-cc/goto-cc
-GOTO_INSTRUMENT=$MALLOB/lib/cbmc/src/goto-instrument/goto-instrument
-TOOL_NAME=MALLOB_CBMC
+
+TOOL_BINARY=../cbmc_minisat/cbmc/src/cbmc/cbmc
+GOTO_CC=../cbmc_minisat/cbmc/src/goto-cc/goto-cc
+GOTO_INSTRUMENT=../cbmc_minisat/cbmc/src/goto-instrument/goto-instrument
+TOOL_NAME=CBMC
 FIND_OPTIONS=""
 
 # function to run the tool
@@ -31,30 +30,80 @@ run()
   fi
   duration=$SECONDS
   export GMON_OUT_PREFIX="cbmc_$gmon_suffix"
-  
-  # Replace spaces with commas in PROPERTY for mallob
-  echo "PROPERTY: $PROPERTY"
-  PROPERTY=$(echo "$PROPERTY" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
-  PROPERTY=$(echo "$PROPERTY" | sed "s/ /,/g")
-  echo "PROPERTY: $PROPERTY"
 
-cd $MALLOB
+#timeout 875 bash -c ' \
+#\
+#ulimit -v 64000000 ; \
+#\
+SAT_TIME=0 ;
+PROCESSING_TIME=0 ; 
+SAT_CALLS=0 ;
 EC=42 ; \
-$TOOL_BINARY -satsolver='k' -noincsat -t=32 -mono-app=cbmc -mono=$LOG.bin -v=4 -compress-models -unwind-loops -cbmc-log=$LOG.ok -cbmc-opts=--no-standard-checks,--slice-formula,--stop-on-fail,--object-bits,$OBJ_BITS,$PROPERTY ; \
+for c in 2 6 12 17 21 40 200 400 1025 2049 268435456 ; do \
+echo "Unwind: $c" | tee -a $LOG.latest ; \
+$TOOL_BINARY --no-standard-checks --slice-formula --unwind $c --stop-on-fail --object-bits $OBJ_BITS $PROPERTY $LOG.bin 2>&1 | tee -a $LOG.latest ; \
+ec=${PIPESTATUS[0]} ; \
 
-if grep -q "s FINAL EC=" $LOG.ok; then EC=$(grep -o "s FINAL EC=[0-9]*" $LOG.ok | tail -n1 | cut -d'=' -f2 | tr -d '[:space:]'); else EC=5; fi ; \
-echo $EC
-echo "t COMPILE_TIME: $duration" | tee -a $LOG.ok
-cd $BACK
-
-#mv $LOG.latest $LOG.ok ; \
-echo "EC=$EC" | tee -a $LOG.ok ; \
-
-if [ ! -s $LOG.ok ] ; then
-  #mv $LOG.latest $LOG.ok ; 
-  echo "EC=42" | tee -a $LOG.ok
+if grep -q "t SAT_TIME: " $LOG.latest; then
+  value=$(grep -o "t SAT_TIME: [0-9]\+\(\.[0-9]\+\)\?" $LOG.latest | tail -n1 | cut -d' ' -f3)
+  SAT_TIME=$(echo "$SAT_TIME + $value" | bc)
 fi
-eval `tail -n 1 $LOG.ok`
+if grep -q "t PROCESSING_TIME: " $LOG.latest; then
+  value=$(grep -o "t PROCESSING_TIME: [0-9]\+\(\.[0-9]\+\)\?" $LOG.latest | tail -n1 | cut -d' ' -f3)
+  PROCESSING_TIME=$(echo "$PROCESSING_TIME + $value" | bc)
+fi
+if grep -q "t SAT_CALLS: " $LOG.latest; then
+  value=$(grep -o "t SAT_CALLS: [0-9]\+" $LOG.latest | tail -n1 | cut -d' ' -f3)
+  SAT_CALLS=$(echo "$SAT_CALLS + $value" | bc)
+fi
+
+if [ $ec -eq 0 ] ; then \
+if ! tail -n 10 $LOG.latest | grep -q "^VERIFICATION SUCCESSFUL$" ; then ec=1 ; else \
+$TOOL_BINARY --no-standard-checks --slice-formula --unwinding-assertions --unwind $c --stop-on-fail --object-bits $OBJ_BITS $PROPERTY $LOG.bin 2>&1 | tee -a $LOG.latest2 ; \
+ec=${PIPESTATUS[0]} ; \
+if [ $ec -ne 0 ] ; then \
+ec=42 ; \
+fi ; \
+ 
+
+if grep -q "t SAT_TIME: " $LOG.latest2; then
+  value=$(grep -o "t SAT_TIME: [0-9]\+\(\.[0-9]\+\)\?" $LOG.latest2 | tail -n1 | cut -d' ' -f3)
+  SAT_TIME=$(echo "$SAT_TIME + $value" | bc)
+fi
+if grep -q "t PROCESSING_TIME: " $LOG.latest2; then
+  value=$(grep -o "t PROCESSING_TIME: [0-9]\+\(\.[0-9]\+\)\?" $LOG.latest2 | tail -n1 | cut -d' ' -f3)
+  PROCESSING_TIME=$(echo "$PROCESSING_TIME + $value" | bc)
+fi
+if grep -q "t SAT_CALLS: " $LOG.latest2; then
+  value=$(grep -o "t SAT_CALLS: [0-9]\+" $LOG.latest2 | tail -n1 | cut -d' ' -f3)
+  SAT_CALLS=$(echo "$SAT_CALLS + $value" | bc)
+fi
+cat $LOG.latest2 >> $LOG.latest ; \
+
+fi ; \
+fi ; \
+if [ $ec -eq 10 ] ; then \
+if ! tail -n 10 $LOG.latest | grep -q "^VERIFICATION FAILED$" ; then ec=1 ; fi ; \
+fi ; \
+\
+case $ec in \
+0) EC=0 ; cat $LOG.latest >> $LOG.ok ; echo "EC=$EC" | tee -a $LOG.ok ; break ;; \
+10) EC=10 ; cat $LOG.latest >> $LOG.ok ; echo "EC=$EC" | tee -a $LOG.ok ; break ;; \
+42) EC=42 ; cat $LOG.latest >> $LOG.ok ; rm -f $LOG.latest ;; \
+*) if [ $EC -ne 0 ] ; then EC=$ec ; cat $LOG.latest >>$LOG.ok ; fi ; echo "EC=$EC" | tee -a $LOG.ok ; break ;; \
+esac ; \
+\
+done \
+#'
+  if [ ! -s $LOG.ok ] ; then
+    mv $LOG.latest $LOG.ok ; echo "EC=42" | tee -a $LOG.ok
+  fi
+  eval `tail -n 1 $LOG.ok`
+  echo "t COMPILE_TIME: $duration" | tee -a $LOG.ok
+  echo "s FINAL EC=$EC" | tee -a $LOG.ok
+  echo "t FINAL SAT_CALLS: $SAT_CALLS" | tee -a $LOG.ok
+  echo "t FINAL SAT_TIME: $(printf "%.3f" "$SAT_TIME")" | tee -a $LOG.ok
+  echo "t FINAL PROCESSING_TIME: $(printf "%.3f" "$PROCESSING_TIME")" | tee -a $LOG.ok
 }
 
 # main tool wrapper script
@@ -221,9 +270,8 @@ export GMON_OUT_PREFIX=`basename ${BM[0]}`.gmon.out
 
 export BM_DIR=`mktemp -d -t ${TOOL_NAME}-benchmark.XXXXXX`
 
-export LOG=$(mktemp -t ${TOOL_NAME}-log.XXXXXX)
+export LOG=`mktemp -t ${TOOL_NAME}-log.XXXXXX`
 trap "rm -rf $LOG $LOG.latest $LOG.ok $LOG.witness $LOG.bin $BM_DIR" EXIT
-
 
 run
 
@@ -231,8 +279,7 @@ if [ ! -s $LOG.ok ] ; then
   exit 1
 fi
 
-echo "LOG: $LOG.ok"
-cat $LOG.ok
+#cat $LOG.ok
 case $EC in
   0) if [[ "$WITNESS_FILE" != "" ]]; then process_graphml $EC > $WITNESS_FILE; \
 fi; echo "TRUE" ;;
